# ldap sample for open ldap, need to rename this file to application-ldap.yml to make it effective
spring:
  ldap:
    base: "dc=secoo,dc=com"
    username: "cn=admin,dc=secoo,dc=com" # 配置管理员账号，用于搜索、匹配用户
    password: "secoo.com"
    searchFilter: "(uid={0})"  # 用户过滤器，登录的时候用这个过滤器来搜索用户
    urls:
      - "ldap://192.168.50.100:389"

ldap:
  mapping: # 配置 ldap 属性
    objectClass: "inetOrgPerson" # ldap 用户 objectClass 配置
    loginId: "uid" # ldap 用户惟一 id，用来作为登录的 id
    userDisplayName: "cn" # ldap 用户名，用来作为显示名
    email: "mail" # ldap 邮箱属性